package com.smartbear.ccollab.service.api.v7001;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-09-20T15:21:45.934+04:00
 * Generated source version: 2.6.2
 */
@WebService(targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", name = "CodeCollaborator")
@XmlSeeAlso({ObjectFactory.class})
public interface CodeCollaborator {

    @RequestWrapper(localName = "uncancelReview", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.UncancelReview")
    @WebMethod
    @ResponseWrapper(localName = "uncancelReviewResponse", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.UncancelReviewResponse")
    public void uncancelReview(
            @WebParam(name = "reviewID", targetNamespace = "")
            int reviewID
    ) throws NotAuthorizedException_Exception, ServerNotInitializedException_Exception, ServiceException_Exception;

    @RequestWrapper(localName = "markDefectExternal", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.MarkDefectExternal")
    @WebMethod
    @ResponseWrapper(localName = "markDefectExternalResponse", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.MarkDefectExternalResponse")
    public void markDefectExternal(
            @WebParam(name = "arg0", targetNamespace = "")
            int arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            java.lang.String arg1
    ) throws NotAuthorizedException_Exception, ServerNotInitializedException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getActionItems", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.GetActionItems")
    @WebMethod
    @ResponseWrapper(localName = "getActionItemsResponse", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.GetActionItemsResponse")
    public java.util.List<com.smartbear.ccollab.service.api.v7001.ActionItem> getActionItems() throws NotAuthorizedException_Exception, ServerNotInitializedException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createComment", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.CreateComment")
    @WebMethod
    @ResponseWrapper(localName = "createCommentResponse", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.CreateCommentResponse")
    public int createComment(
            @WebParam(name = "reviewID", targetNamespace = "")
            int reviewID,
            @WebParam(name = "comment", targetNamespace = "")
            java.lang.String comment
    ) throws NotAuthorizedException_Exception, ServerNotInitializedException_Exception, ServiceException_Exception;

    @RequestWrapper(localName = "acceptAt", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.AcceptAt")
    @WebMethod
    @ResponseWrapper(localName = "acceptAtResponse", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.AcceptAtResponse")
    public void acceptAt(
            @WebParam(name = "location", targetNamespace = "")
            com.smartbear.ccollab.service.api.v7001.Location location
    ) throws NotAuthorizedException_Exception, ServerNotInitializedException_Exception, ServiceException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkLoginTicket", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.CheckLoginTicket")
    @WebMethod
    @ResponseWrapper(localName = "checkLoginTicketResponse", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.CheckLoginTicketResponse")
    public boolean checkLoginTicket() throws ServerNotInitializedException_Exception;

    @RequestWrapper(localName = "acceptConversation", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.AcceptConversation")
    @WebMethod
    @ResponseWrapper(localName = "acceptConversationResponse", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.AcceptConversationResponse")
    public void acceptConversation(
            @WebParam(name = "conversationID", targetNamespace = "")
            int conversationID
    ) throws NotAuthorizedException_Exception, ServerNotInitializedException_Exception, ServiceException_Exception;

    @RequestWrapper(localName = "deleteDefect", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.DeleteDefect")
    @WebMethod
    @ResponseWrapper(localName = "deleteDefectResponse", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.DeleteDefectResponse")
    public void deleteDefect(
            @WebParam(name = "arg0", targetNamespace = "")
            int arg0
    ) throws NotAuthorizedException_Exception, ServerNotInitializedException_Exception;

    @RequestWrapper(localName = "reopenReview", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.ReopenReview")
    @WebMethod
    @ResponseWrapper(localName = "reopenReviewResponse", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.ReopenReviewResponse")
    public void reopenReview(
            @WebParam(name = "reviewID", targetNamespace = "")
            int reviewID
    ) throws NotAuthorizedException_Exception, ServerNotInitializedException_Exception, ServiceException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLoginTicket", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.GetLoginTicket")
    @WebMethod
    @ResponseWrapper(localName = "getLoginTicketResponse", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.GetLoginTicketResponse")
    public java.lang.String getLoginTicket(
            @WebParam(name = "login", targetNamespace = "")
            java.lang.String login,
            @WebParam(name = "password", targetNamespace = "")
            java.lang.String password
    ) throws ServerNotInitializedException_Exception;

    @RequestWrapper(localName = "cancelReview", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.CancelReview")
    @WebMethod
    @ResponseWrapper(localName = "cancelReviewResponse", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.CancelReviewResponse")
    public void cancelReview(
            @WebParam(name = "reviewID", targetNamespace = "")
            int reviewID
    ) throws NotAuthorizedException_Exception, ServerNotInitializedException_Exception, ServiceException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCurrentUser", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.GetCurrentUser")
    @WebMethod
    @ResponseWrapper(localName = "getCurrentUserResponse", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.GetCurrentUserResponse")
    public com.smartbear.ccollab.service.api.v7001.User getCurrentUser() throws NotAuthorizedException_Exception, ServerNotInitializedException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createCommentAt", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.CreateCommentAt")
    @WebMethod
    @ResponseWrapper(localName = "createCommentAtResponse", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.CreateCommentAtResponse")
    public int createCommentAt(
            @WebParam(name = "location", targetNamespace = "")
            com.smartbear.ccollab.service.api.v7001.Location location,
            @WebParam(name = "comment", targetNamespace = "")
            java.lang.String comment
    ) throws NotAuthorizedException_Exception, ServerNotInitializedException_Exception, ServiceException_Exception;

    @RequestWrapper(localName = "markConversationRead", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.MarkConversationRead")
    @WebMethod
    @ResponseWrapper(localName = "markConversationReadResponse", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.MarkConversationReadResponse")
    public void markConversationRead(
            @WebParam(name = "conversationID", targetNamespace = "")
            int conversationID
    ) throws NotAuthorizedException_Exception, ServerNotInitializedException_Exception, ServiceException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createDefect", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.CreateDefect")
    @WebMethod
    @ResponseWrapper(localName = "createDefectResponse", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.CreateDefectResponse")
    public int createDefect(
            @WebParam(name = "reviewID", targetNamespace = "")
            int reviewID,
            @WebParam(name = "comment", targetNamespace = "")
            java.lang.String comment,
            @WebParam(name = "customField", targetNamespace = "")
            java.util.List<com.smartbear.ccollab.service.api.v7001.CustomField> customField
    ) throws NotAuthorizedException_Exception, ServerNotInitializedException_Exception, ServiceException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getProductVersion", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.GetProductVersion")
    @WebMethod
    @ResponseWrapper(localName = "getProductVersionResponse", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.GetProductVersionResponse")
    public java.lang.String getProductVersion();

    @RequestWrapper(localName = "markDefectOpen", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.MarkDefectOpen")
    @WebMethod
    @ResponseWrapper(localName = "markDefectOpenResponse", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.MarkDefectOpenResponse")
    public void markDefectOpen(
            @WebParam(name = "arg0", targetNamespace = "")
            int arg0
    ) throws NotAuthorizedException_Exception, ServerNotInitializedException_Exception;

    @RequestWrapper(localName = "waitReview", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.WaitReview")
    @WebMethod
    @ResponseWrapper(localName = "waitReviewResponse", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.WaitReviewResponse")
    public void waitReview(
            @WebParam(name = "reviewID", targetNamespace = "")
            int reviewID,
            @WebParam(name = "waitingUntil", targetNamespace = "")
            com.smartbear.ccollab.service.api.v7001.ActivityTypeSpec waitingUntil
    ) throws NotAuthorizedException_Exception, ServerNotInitializedException_Exception, ServiceException_Exception;

    @RequestWrapper(localName = "rejectReview", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.RejectReview")
    @WebMethod
    @ResponseWrapper(localName = "rejectReviewResponse", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.RejectReviewResponse")
    public void rejectReview(
            @WebParam(name = "reviewID", targetNamespace = "")
            int reviewID,
            @WebParam(name = "reason", targetNamespace = "")
            java.lang.String reason
    ) throws NotAuthorizedException_Exception, ServerNotInitializedException_Exception, ServiceException_Exception;

    @RequestWrapper(localName = "updateDefect", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.UpdateDefect")
    @WebMethod
    @ResponseWrapper(localName = "updateDefectResponse", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.UpdateDefectResponse")
    public void updateDefect(
            @WebParam(name = "defectID", targetNamespace = "")
            int defectID,
            @WebParam(name = "comment", targetNamespace = "")
            java.lang.String comment,
            @WebParam(name = "customField", targetNamespace = "")
            java.util.List<com.smartbear.ccollab.service.api.v7001.CustomField> customField
    ) throws NotAuthorizedException_Exception, ServerNotInitializedException_Exception, ServiceException_Exception;

    @RequestWrapper(localName = "setAnnotation", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.SetAnnotation")
    @WebMethod
    @ResponseWrapper(localName = "setAnnotationResponse", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.SetAnnotationResponse")
    public void setAnnotation(
            @WebParam(name = "reviewID", targetNamespace = "")
            int reviewID,
            @WebParam(name = "versionID", targetNamespace = "")
            int versionID,
            @WebParam(name = "comment", targetNamespace = "")
            java.lang.String comment
    ) throws NotAuthorizedException_Exception, ServerNotInitializedException_Exception, ServiceException_Exception;

    @RequestWrapper(localName = "updateReview", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.UpdateReview")
    @WebMethod
    @ResponseWrapper(localName = "updateReviewResponse", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.UpdateReviewResponse")
    public void updateReview(
            @WebParam(name = "reviewID", targetNamespace = "")
            int reviewID,
            @WebParam(name = "title", targetNamespace = "")
            java.lang.String title,
            @WebParam(name = "groupGuid", targetNamespace = "")
            java.lang.String groupGuid,
            @WebParam(name = "deadline", targetNamespace = "")
            javax.xml.datatype.XMLGregorianCalendar deadline,
            @WebParam(name = "displayChangeListAs", targetNamespace = "")
            com.smartbear.ccollab.service.api.v7001.DisplayChangeListAsSpec displayChangeListAs,
            @WebParam(name = "accessibleBy", targetNamespace = "")
            com.smartbear.ccollab.service.api.v7001.ReviewAccessSpec accessibleBy,
            @WebParam(name = "templateName", targetNamespace = "")
            java.lang.String templateName
    ) throws NotAuthorizedException_Exception, ServerNotInitializedException_Exception, ServiceException_Exception;

    @RequestWrapper(localName = "finishReviewPhase", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.FinishReviewPhase")
    @WebMethod
    @ResponseWrapper(localName = "finishReviewPhaseResponse", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.FinishReviewPhaseResponse")
    public void finishReviewPhase(
            @WebParam(name = "reviewID", targetNamespace = "")
            int reviewID,
            @WebParam(name = "finishedUntil", targetNamespace = "")
            com.smartbear.ccollab.service.api.v7001.ActivityTypeSpec finishedUntil
    ) throws NotAuthorizedException_Exception, ServerNotInitializedException_Exception, ServiceException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createReview", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.CreateReview")
    @WebMethod
    @ResponseWrapper(localName = "createReviewResponse", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.CreateReviewResponse")
    public int createReview(
            @WebParam(name = "userlogin", targetNamespace = "")
            java.lang.String userlogin
    ) throws NotAuthorizedException_Exception, ServerNotInitializedException_Exception, ServiceException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findLatestVersion", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.FindLatestVersion")
    @WebMethod
    @ResponseWrapper(localName = "findLatestVersionResponse", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.FindLatestVersionResponse")
    public int findLatestVersion(
            @WebParam(name = "reviewID", targetNamespace = "")
            int reviewID,
            @WebParam(name = "filePath", targetNamespace = "")
            java.lang.String filePath
    ) throws NotAuthorizedException_Exception, ServerNotInitializedException_Exception, ServiceException_Exception;

    @RequestWrapper(localName = "redactComment", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.RedactComment")
    @WebMethod
    @ResponseWrapper(localName = "redactCommentResponse", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.RedactCommentResponse")
    public void redactComment(
            @WebParam(name = "commentID", targetNamespace = "")
            int commentID
    ) throws NotAuthorizedException_Exception, ServerNotInitializedException_Exception, ServiceException_Exception;

    @RequestWrapper(localName = "pokeReviewParticipant", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.PokeReviewParticipant")
    @WebMethod
    @ResponseWrapper(localName = "pokeReviewParticipantResponse", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.PokeReviewParticipantResponse")
    public void pokeReviewParticipant(
            @WebParam(name = "reviewID", targetNamespace = "")
            int reviewID,
            @WebParam(name = "participantLogin", targetNamespace = "")
            java.lang.String participantLogin
    ) throws NotAuthorizedException_Exception, ServerNotInitializedException_Exception;

    @RequestWrapper(localName = "accept", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.Accept")
    @WebMethod
    @ResponseWrapper(localName = "acceptResponse", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.AcceptResponse")
    public void accept(
            @WebParam(name = "reviewID", targetNamespace = "")
            int reviewID
    ) throws NotAuthorizedException_Exception, ServerNotInitializedException_Exception, ServiceException_Exception;

    @RequestWrapper(localName = "updateReviewCustomFields", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.UpdateReviewCustomFields")
    @WebMethod
    @ResponseWrapper(localName = "updateReviewCustomFieldsResponse", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.UpdateReviewCustomFieldsResponse")
    public void updateReviewCustomFields(
            @WebParam(name = "reviewID", targetNamespace = "")
            int reviewID,
            @WebParam(name = "customField", targetNamespace = "")
            java.util.List<com.smartbear.ccollab.service.api.v7001.CustomField> customField
    ) throws NotAuthorizedException_Exception, ServerNotInitializedException_Exception, ServiceException_Exception;

    @RequestWrapper(localName = "markDefectNotExternal", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.MarkDefectNotExternal")
    @WebMethod
    @ResponseWrapper(localName = "markDefectNotExternalResponse", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.MarkDefectNotExternalResponse")
    public void markDefectNotExternal(
            @WebParam(name = "arg0", targetNamespace = "")
            int arg0
    ) throws NotAuthorizedException_Exception, ServerNotInitializedException_Exception;

    @RequestWrapper(localName = "deleteReview", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.DeleteReview")
    @WebMethod
    @ResponseWrapper(localName = "deleteReviewResponse", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.DeleteReviewResponse")
    public void deleteReview(
            @WebParam(name = "reviewID", targetNamespace = "")
            int reviewID
    ) throws NotAuthorizedException_Exception, ServerNotInitializedException_Exception, ServiceException_Exception;

    @RequestWrapper(localName = "startAnnotatingPhase", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.StartAnnotatingPhase")
    @WebMethod
    @ResponseWrapper(localName = "startAnnotatingPhaseResponse", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.StartAnnotatingPhaseResponse")
    public void startAnnotatingPhase(
            @WebParam(name = "reviewID", targetNamespace = "")
            int reviewID
    ) throws NotAuthorizedException_Exception, ServerNotInitializedException_Exception, ServiceException_Exception;

    @RequestWrapper(localName = "markDefectFixed", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.MarkDefectFixed")
    @WebMethod
    @ResponseWrapper(localName = "markDefectFixedResponse", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.MarkDefectFixedResponse")
    public void markDefectFixed(
            @WebParam(name = "arg0", targetNamespace = "")
            int arg0
    ) throws NotAuthorizedException_Exception, ServerNotInitializedException_Exception;

    @RequestWrapper(localName = "addReviewURLs", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.AddReviewURLs")
    @WebMethod
    @ResponseWrapper(localName = "addReviewURLsResponse", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.AddReviewURLsResponse")
    public void addReviewURLs(
            @WebParam(name = "reviewID", targetNamespace = "")
            int reviewID,
            @WebParam(name = "url", targetNamespace = "")
            java.util.List<java.lang.String> url,
            @WebParam(name = "uploadComment", targetNamespace = "")
            java.lang.String uploadComment
    ) throws NotAuthorizedException_Exception, ServerNotInitializedException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createDefectAt", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.CreateDefectAt")
    @WebMethod
    @ResponseWrapper(localName = "createDefectAtResponse", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/", className = "com.smartbear.ccollab.service.api.v7001.CreateDefectAtResponse")
    public int createDefectAt(
            @WebParam(name = "location", targetNamespace = "")
            com.smartbear.ccollab.service.api.v7001.Location location,
            @WebParam(name = "comment", targetNamespace = "")
            java.lang.String comment,
            @WebParam(name = "customField", targetNamespace = "")
            java.util.List<com.smartbear.ccollab.service.api.v7001.CustomField> customField
    ) throws NotAuthorizedException_Exception, ServerNotInitializedException_Exception, ServiceException_Exception;
}
