package com.smartbear.ccollab.service.api.v7001;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-09-20T15:21:45.900+04:00
 * Generated source version: 2.6.2
 */

@WebFault(name = "NotAuthorizedException", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/")
public class NotAuthorizedException_Exception extends Exception {

    private com.smartbear.ccollab.service.api.v7001.NotAuthorizedException notAuthorizedException;

    public NotAuthorizedException_Exception() {
        super();
    }

    public NotAuthorizedException_Exception(String message) {
        super(message);
    }

    public NotAuthorizedException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public NotAuthorizedException_Exception(String message, com.smartbear.ccollab.service.api.v7001.NotAuthorizedException notAuthorizedException) {
        super(message);
        this.notAuthorizedException = notAuthorizedException;
    }

    public NotAuthorizedException_Exception(String message, com.smartbear.ccollab.service.api.v7001.NotAuthorizedException notAuthorizedException, Throwable cause) {
        super(message, cause);
        this.notAuthorizedException = notAuthorizedException;
    }

    public com.smartbear.ccollab.service.api.v7001.NotAuthorizedException getFaultInfo() {
        return this.notAuthorizedException;
    }
}
