package com.smartbear.ccollab.service.api.v7001;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-09-20T15:21:45.911+04:00
 * Generated source version: 2.6.2
 */

@WebFault(name = "ServerNotInitializedException", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/")
public class ServerNotInitializedException_Exception extends Exception {

    private com.smartbear.ccollab.service.api.v7001.ServerNotInitializedException serverNotInitializedException;

    public ServerNotInitializedException_Exception() {
        super();
    }

    public ServerNotInitializedException_Exception(String message) {
        super(message);
    }

    public ServerNotInitializedException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ServerNotInitializedException_Exception(String message, com.smartbear.ccollab.service.api.v7001.ServerNotInitializedException serverNotInitializedException) {
        super(message);
        this.serverNotInitializedException = serverNotInitializedException;
    }

    public ServerNotInitializedException_Exception(String message, com.smartbear.ccollab.service.api.v7001.ServerNotInitializedException serverNotInitializedException, Throwable cause) {
        super(message, cause);
        this.serverNotInitializedException = serverNotInitializedException;
    }

    public com.smartbear.ccollab.service.api.v7001.ServerNotInitializedException getFaultInfo() {
        return this.serverNotInitializedException;
    }
}
