package com.smartbear.ccollab.service.api.v7001;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-09-20T15:21:45.920+04:00
 * Generated source version: 2.6.2
 */

@WebFault(name = "ServiceException", targetNamespace = "http://v7001.api.service.ccollab.smartbear.com/")
public class ServiceException_Exception extends Exception {

    private com.smartbear.ccollab.service.api.v7001.ServiceException serviceException;

    public ServiceException_Exception() {
        super();
    }

    public ServiceException_Exception(String message) {
        super(message);
    }

    public ServiceException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ServiceException_Exception(String message, com.smartbear.ccollab.service.api.v7001.ServiceException serviceException) {
        super(message);
        this.serviceException = serviceException;
    }

    public ServiceException_Exception(String message, com.smartbear.ccollab.service.api.v7001.ServiceException serviceException, Throwable cause) {
        super(message, cause);
        this.serviceException = serviceException;
    }

    public com.smartbear.ccollab.service.api.v7001.ServiceException getFaultInfo() {
        return this.serviceException;
    }
}
